version: '3.8'

services:
  db:
    image: postgres:16.3
    container_name: postgres-db-social
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: social
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

volumes:
  db_data: